print("Hello, Im deathbot, welcome to the afterlife!")
print()
print("What was your name?")
myName = input()
print("Well met "+ myName )
print()
print("Your journey was long, but how long? (months)")
myTime = input()
print("Your tombestone will read, Here lies "+myName +" who died short of "+(str(int(myTime)+1))+" months past the end of the world.")
print()
print(myName+"'s name is " +str(int(len(myName)))+" letters long, hope that fits on a cross.")
print()
myTime = (int(myTime)+1)
print( "" + (str(int(myTime))) + " months is about " + (str(int((myTime)*30))) + " days of hell on the road.")
print( "how many zombies have you killed?")
myZomb = input()
print( (str(int(myZomb))) + " is barely enough to make a dent in this world.")